<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FocusRecorder.Application\FocusRecorder.Application.csproj" />
    <ProjectReference Include="..\FocusRecorder.Infrastructure\FocusRecorder.Infrastructure.csproj" />
  </ItemGroup>
</Project>
